2025-03-12 21:20:59,378 - INFO - Processando DELETE para a tabela: Fato_UR
2025-03-12 21:20:59,389 - INFO - \u2705 Backup realizado para a tabela Fato_UR - PerÌodo: 2025-03
2025-03-12 21:20:59,392 - INFO - Linhas removidas com sucesso para o perÌodo 2025-03!
2025-03-12 21:20:59,479 - INFO - Processando DELETE para a tabela: Fato_UR
2025-03-12 21:20:59,482 - INFO - \u2705 Backup realizado para a tabela Fato_UR - PerÌodo: 2025-03
2025-03-12 21:20:59,483 - INFO - Linhas removidas com sucesso para o perÌodo 2025-03!
2025-03-12 21:20:59,572 - INFO - Processando DELETE para a tabela: Fato_UR
2025-03-12 21:20:59,575 - INFO - \u2705 Backup realizado para a tabela Fato_UR - PerÌodo: 2025-03
2025-03-12 21:20:59,576 - INFO - Linhas removidas com sucesso para o perÌodo 2025-03!
2025-03-12 21:23:40,326 - INFO - Processando DELETE para a tabela: Fato_UR
2025-03-12 21:23:40,326 - INFO - \u2705 Backup realizado para a tabela Fato_UR - PerÌodo: 2025-03
2025-03-12 21:23:40,326 - INFO - Linhas removidas com sucesso para o perÌodo 2025-03!
2025-03-12 21:23:40,328 - INFO - Processando DELETE para a tabela: Fato_UR
2025-03-12 21:23:40,328 - INFO - \u2705 Backup realizado para a tabela Fato_UR - PerÌodo: 2099-12
2025-03-12 21:23:40,329 - INFO - Linhas removidas com sucesso para o perÌodo 2099-12!
2025-03-12 21:28:28,659 - INFO - Processando DELETE para a tabela: Fato_UR
2025-03-12 21:28:28,659 - INFO - \u2705 Backup realizado para a tabela Fato_UR - PerÌodo: 2025-03
2025-03-12 21:28:28,660 - INFO - Linhas removidas com sucesso para o perÌodo 2025-03!
2025-03-12 21:28:28,661 - INFO - Processando DELETE para a tabela: Fato_UR
2025-03-12 21:28:28,662 - INFO - \u2705 Backup realizado para a tabela Fato_UR - PerÌodo: 2099-12
2025-03-12 21:28:28,662 - INFO - Linhas removidas com sucesso para o perÌodo 2099-12!
2025-03-12 21:28:28,866 - INFO - Processando DELETE para a tabela: Fato_UR
2025-03-12 21:28:28,866 - INFO - \u2705 Backup realizado para a tabela Fato_UR - PerÌodo: 2025-03
2025-03-12 21:28:28,866 - INFO - Linhas removidas com sucesso para o perÌodo 2025-03!
2025-03-12 21:28:28,963 - INFO - Processando DELETE para a tabela: Fato_UR
2025-03-12 21:28:28,968 - INFO - \u2705 Backup realizado para a tabela Fato_UR - PerÌodo: 2025-03
2025-03-12 21:28:28,968 - INFO - Linhas removidas com sucesso para o perÌodo 2025-03!
2025-03-12 21:28:29,065 - INFO - Processando DELETE para a tabela: Fato_UR
2025-03-12 21:28:29,069 - INFO - \u2705 Backup realizado para a tabela Fato_UR - PerÌodo: 2025-03
2025-03-12 21:28:29,070 - INFO - Linhas removidas com sucesso para o perÌodo 2025-03!
2025-03-12 21:28:29,163 - INFO - Processando DELETE para a tabela: Fato_UR
2025-03-12 21:28:29,168 - INFO - \u2705 Backup realizado para a tabela Fato_UR - PerÌodo: 2025-03
2025-03-12 21:28:29,168 - INFO - Linhas removidas com sucesso para o perÌodo 2025-03!
2025-03-13 14:49:04,467 - ERROR - ‚ùå ERRO ao deletar da tabela Fato_UR: ERRO:  n√£o existe a rela√ß√£o "fato_ur"
LINE 1: DELETE FROM Fato_UR WHERE ano_mes = '2025-03' RETURNING *;
                    ^

2025-03-13 14:55:20,559 - INFO - ‚úÖ DELETE executado com sucesso - Tabela: Fato_UR | Per√≠odo: 2025-03 | Registros removidos: 0
2025-03-13 14:56:42,629 - INFO - ‚úÖ DELETE executado com sucesso - Tabela: Fato_UR | Per√≠odo: 2025-03 | Registros removidos: 1
2025-03-13 14:58:46,023 - INFO - ‚úÖ DELETE executado com sucesso - Tabela: Fato_UR | Per√≠odo: 2025-03 | Registros removidos: 3
2025-03-13 15:16:47,706 - INFO - ‚úÖ DELETE executado com sucesso - Tabela: ['Fato_UR'] | Per√≠odo: 2025-03 | Registros removidos: <MagicMock name='get_connection().__enter__().cursor().__enter__().rowcount' id='1792307550864'>
2025-03-13 15:16:47,707 - ERROR - ‚ùå ERRO ao deletar da tabela ['Fato_UR']: '>' not supported between instances of 'MagicMock' and 'int'
2025-03-13 15:16:47,716 - INFO - ‚úÖ DELETE executado com sucesso - Tabela: ['Fato_UR'] | Per√≠odo: 2099-12 | Registros removidos: <MagicMock name='get_connection().__enter__().cursor().__enter__().rowcount' id='1792307558256'>
2025-03-13 15:16:47,716 - ERROR - ‚ùå ERRO ao deletar da tabela ['Fato_UR']: '>' not supported between instances of 'MagicMock' and 'int'
2025-03-13 15:16:47,946 - INFO - ‚úÖ DELETE executado com sucesso - Tabela: ['Fato_UR'] | Per√≠odo: 2025-03 | Registros removidos: <MagicMock name='get_connection().__enter__().cursor().__enter__().rowcount' id='1792311760208'>
2025-03-13 15:16:47,947 - ERROR - ‚ùå ERRO ao deletar da tabela ['Fato_UR']: '>' not supported between instances of 'MagicMock' and 'int'
2025-03-13 15:16:48,068 - ERROR - ‚ùå ERRO ao deletar da tabela ['Fato_UR']: ERRO:  n√£o existe a rela√ß√£o "['Fato_UR']"
LINE 1: DELETE FROM "['Fato_UR']" WHERE ano_mes = '2025-03' RETURNIN...
                    ^

